import { NextUIProvider } from "@nextui-org/react";
import Nav from "./_components/nav/Nav";
import "./globals.css";
import Header from "@/app/_components/header/Header";
import { getIds } from "@/actions/getIds";
import AppProvider from "./context/AppProvider";
import { Id_PER_PAGE } from "@/config/constants";
import { authenticateUser } from "@/utils/authenticateMe";

export const metadata = {
  title: "FindID Biggest Marketing",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const isAuthenticateUser = await authenticateUser();
  // const initialIds = await getIds(0, Id_PER_PAGE);

  return (
    <html lang="fa" dir="rtl">
      <head>
        <link
          rel="icon"
          href="/images/logo.png"
          sizes="any"
          className="h-64 w-64"
        />
      </head>
      <body>
        <div>
          <AppProvider
            isAuthenticateUser={JSON.parse(JSON.stringify(isAuthenticateUser))}
          >
            <Header
              isAuthenticateUser={JSON.parse(
                JSON.stringify(isAuthenticateUser)
              )}
            />
            <div className="p-4 bg-header min-h-screen ">
              <div className="bg-[url('/images/bg-nav.svg')] bg-fixed rounded-2xl  min-h-screen ">
                {children}
              </div>
            </div>
          </AppProvider>
        </div>
      </body>
    </html>
  );
}
