import { getIds } from "@/actions/getIds";
import AppProvider from "@/app/context/AppProvider";
import { Id_PER_PAGE } from "@/config/constants";
import { authenticateUser } from "@/utils/authenticateMe";
import { addSiteJsonLd } from "@/utils/schemasSeo";
import { redirect } from "next/navigation";

export const metadata = {
  title: "پروفایل",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const isAuthenticateUser = await authenticateUser();
  if (!isAuthenticateUser) {
    redirect("/");
  }
  // const initialIds = await getIds(0, Id_PER_PAGE);
  return (
    <div className="">
      <AppProvider
        isAuthenticateUser={JSON.parse(JSON.stringify(isAuthenticateUser))}
      >
        {children}
      </AppProvider>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={addSiteJsonLd()}
        key="site-jsonld"
      />
    </div>
  );
}
