import AppProvider from "@/app/context/AppProvider";
import { authenticateUser } from "@/utils/authenticateMe";
import { redirect } from "next/navigation";

export const metadata = {
  title: "ثبت آگهی جدید",
  description: "Generated by create next app",
};

export default async function newLayout({ children }) {
  const isAuthenticateUser = await authenticateUser();
  if (!isAuthenticateUser) {
    redirect("/");
  }
  return (
    <>
      <AppProvider
        isAuthenticateUser={JSON.parse(JSON.stringify(isAuthenticateUser))}
      >
        {children}
      </AppProvider>
    </>
  );
}
